[package]
name = "rust-sdl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gl = "0.14.0"
glam = "0.23.0"
glm = "0.2.3"
sdl2 = { version = "0.35.2", features = ["gfx", "image", "ttf"] }
