[package]
name = "rust-sdl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sdl2 = "0.34.5"
gl = "0.14.0"
glutin = "0.26.0"
nalgebra-glm = "0.18.0"
